// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://echgzwzlbdurljmudssw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVjaGd6d3psYmR1cmxqbXVkc3N3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExMTIyMTEsImV4cCI6MjA2NjY4ODIxMX0.dmY6VYhubIf5FBtEholRHLwDdHax3Oda-_RQpoR5EsM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);